### ISSUE TITLE
Install image logo 404's

### ISSUE THREAD

**Issue by mdroidian** [samepage-network/samepage.network#72]
https://samepage.network/install?id=logseq

![image](https://user-images.githubusercontent.com/3792666/236369583-f3c2909b-7964-4129-8657-993b8adc636b.png)

```
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: assets/logseq/logo.png
RequestId: *****
HostId: *********
An Error Occurred While Attempting to Retrieve a Custom Error Document
Code: NoSuchKey
Message: The specified key does not exist.
Key: 404.html
```

**Comment by dvargas92495** [comment]
Damn didn't work - will pick back up tm

**Comment by dvargas92495** [comment]
pushed a workaround for now - still need to work on the `/assets/$app/$asset.tsx` route at a later point
