### ISSUE TITLE
Investigate backend debugging in VSCode

### ISSUE THREAD

**Issue by dvargas92495** [samepage-network/samepage.network#99]

**Comment by mdroidian** [comment]
So I got a few methods to work.

1. Auto Attach
2. JavaScript Debug Terminal
3. launch.json

# Auto Attach
Run Command Palette `Debug: Toggle Auto Attach` > `Smart` / `Always`
`npm start`

# JavaScript Debug Terminal
Command Palette `Debug: JavaScript Debug Terminal`
or 
![image](https://github.com/samepage-network/samepage.network/assets/3792666/d91a98a2-62c4-4352-a973-4e229a3a5349)

`npm start`

# launch.json
Add the following to `.vscode/launch.json` (adjust file location where necessary)

```
{
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Samepage Network Debug",
      "runtimeArgs": ["-r", "ts-node/register"],
      "args": ["${workspaceFolder}/samepage.network/scripts/cli.ts", "start"],
      "cwd": "${workspaceFolder}/samepage.network"
    }
  ]
}
```
Then `F5`
or
Go to the `Run and Debug` tab
![image](https://github.com/samepage-network/samepage.network/assets/3792666/596ca52a-7cbf-4ba7-8c7f-6f7396f07139)

**Comment by mdroidian** [comment]
I'm going to run with `#2` and `#3` and will reopen this if they are unreliable.

**Comment by dvargas92495** [comment]
Number 3 is the ideal solution - I think there's a way to share configs like this in the repo directly via a `.vscode` folder or something of the sort - would love to have that added
